package nahama.starwoods.core;

import nahama.starwoods.StarWoodsModCore;
import cpw.mods.fml.common.ModMetadata;

public class StarWoodsInfoCore {

	public static void loadInfo(ModMetadata meta) {
		meta.modId = StarWoodsModCore.MODID;
		meta.name = StarWoodsModCore.MODNAME;
		meta.description ="This mod adds many useful trees.";
		meta.version =StarWoodsModCore.VERSION ;
		meta.url = "http://www63.atwiki.jp/akasatanahama/pages/73.html";
		meta.authorList.add("Akasata Nahama");
		meta.credits = "\"Takumi Craft\" is making by Tom Kate.";
		meta.logoFile ="assets/starwoods/logo.png";
		meta.autogenerated = false;
	}
}
