package nahama.starwoods.core;

import cpw.mods.fml.common.ModMetadata;
import nahama.starwoods.StarWoodsCore;

public class StarWoodsInfoCore {

	/** MODの情報を登録する処理。 */
	public static void registerInfo(ModMetadata meta) {
		meta.modId = StarWoodsCore.MODID;
		meta.name = StarWoodsCore.MODNAME;
		meta.description = "This mod can add many useful trees.";
		meta.version = StarWoodsCore.VERSION;
		meta.url = "http://www63.atwiki.jp/akasatanahama/pages/73.html";
		meta.authorList.add("Akasata Nahama");
		meta.logoFile = "assets/starwoods/logo.png";
		meta.autogenerated = false;
	}

}
